name: Test Nginx Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag paul-nginx:$(date +%m-%d-%y)
    - name: Push Docker Image
      with:
        image: woodie03/test-nginx
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrest.DOCKER_PASSWORD }}
