name: Test Nginx Image

on:
  push:
    branches: [ "main" ]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag paul-nginx:$(date +%m-%d-%y)
      
    - name: Login to Docker
      uses: docker/login-action@v3
      #env:
      #  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      with: 
        image: woodie03/test-nginx
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        

