name: Test Nginx Image

on:
  push:
    branches: [ "main" ]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u ${{ DOCKER_USERNAME }} -p ${{ DOCKER_PASSWORD }}
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag paul-nginx:$(date +%m-%d-%y)
    - name: Push Docker Image
      run: docker push woodie03/test-nginx
